id: 1d51578e497c4f74943158f73836d138
initial_creation_type: ocr
source_metadata:
  volumes:
    fb51adf951b944f0a92a2922d9e4c11d:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ''
      total_pages: 1734
      volume_number: 34
